services:
  - type: web
    name: lock-it-lending
    env: static
    staticPublishPath: build
    buildCommand: npm run build
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
