#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "develop" ]; then
  echo "Running full check for $BRANCH..."
  npm run check-all
else
  echo "Skipping full check on branch '$BRANCH'"
fi
